[en]
languageName = "English"
languagedirection = "ltr"
title = "Akumatic"
weight = 1

[en.params.sidebar]
subtitle = ""

[en.params.footer]
customText = ""

[en.params.dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006"

[de]
languageName = "Deutsch"
languagedirection = "ltr"
title = "Akumatic"
weight = 2

[de.params.sidebar]
subtitle = ""

[de.params.footer]
customText = ""

[de.params.dateFormat]
published = "02. January 2006"
lastUpdated = "02. January 2006"
