# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/Akumatic"
weight = 1

[social.params]
icon = "brand-github"

[[social]]
identifier = "reddit"
name = "Reddit"
url = "https://www.reddit.com/user/aku-matic/"
weight = 2

[social.params]
icon = "brand-reddit"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:contact@akumatic.eu"
weight = 3

[social.params]
icon = "mail"
